
- path: /releases/name=os-conf?
  type: replace
  value:
    name: os-conf
    version: ((os_conf_version))
    url: https://bosh.io/d/github.com/cloudfoundry/os-conf-release?v=((os_conf_version))
    sha1: ((os_conf_sha1))

- path: /instance_groups/name=k8s/jobs/name=pre-start-script?
  type: replace
  value:
    name: pre-start-script
    release: os-conf
    properties:
      script: |
        #!/usr/bin/env bash
        set -ex
        exec 2>&1

        # install Bash completion for 'kubectl' and the 'k' alias
        if ! grep -qF kubectl ~/.bashrc; then
            echo >> ~/.bashrc
            cat >> ~/.bashrc <<'EOF'
        export PATH=$PATH:/var/vcap/packages/k8s/bin
        source <(kubectl completion bash)
        alias k=kubectl
        complete -o default -F __start_kubectl k
        EOF
        fi

        # Vim version is old and needs upgrading for our config to properly apply
        # Git is required for krew to work
        idx=0
        while fuser /var/lib/dpkg/lock{,-frontend} >/dev/null 2>&1 ; do
            echo "Waiting for other software install to finish (${idx}s elapsed)..."
            sleep 2
            idx=$(expr ${idx} + 2 )
        done
        export DEBIAN_FRONTEND="noninteractive"
        apt-get update -qq
        apt-get install -y -qq "vim" "git"

        # Enforce curated Vim config for editing YAML files appropriately
        cat > ~/.vimrc <<'EOF'
        syntax on
        set autoindent
        set expandtab
        set number
        set shiftwidth=2
        set softtabstop=2
        set nowrap
        set laststatus=2
        EOF

        # install krew
        export PATH=$PATH:/var/vcap/packages/k8s/bin # make sure we have kubectl
        cd ~ # kludge: 'cd' alone fails because HOME is not set during 'pre-start' execution
        OS="$(uname | tr '[:upper:]' '[:lower:]')"
        ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"
        KREW="krew-${OS}_${ARCH}"
        if [[ ! -f "${KREW}.tar.gz" ]]; then
            curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz"
        fi
        if [[ ! -x "${KREW}" ]]; then
            tar zxvf "${KREW}.tar.gz"
        fi
        ./"${KREW}" install krew
        echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> ~/.bashrc

        # The 'view-allocations' plugin requires a .kube/config
        mkdir -p ~/.kube
        cat > ~/.kube/config <<'EOF'
        kind: Config
        apiVersion: v1
        users:
          - name: admin
            user: {}
        clusters:
          - name: local
            cluster:
              server: http://127.0.0.1:8080
        contexts:
          - name: default
            context:
              user: admin
              cluster: local
        current-context: default
        EOF

        # useful plugins: view-allocations, neat.
