name: labernetes

instance_groups:
  - name:      k8s
    instances: 3
    azs:       [z1,z2,z3]
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    vm_extensions:
      - kubelet
    persistent_disk: 20_000
    stemcell:  default
    networks:
      - name: default

    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          apiserver:
            flags:
              - audit-log-maxage: 5
            additional-sans:
              - 10.245.0.1
            audit-policy:
              apiVersion: audit.k8s.io/v1
              kind: Policy
              rules:
                - level: Request
          cluster:
            name: labernetes
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))
          cert-manager:
            enabled: yes
            ca:
              certificate: ((tls-cm.certificate))
              key:         ((tls-cm.private_key))

      - name: lb
        release: k8s

      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: net-flannel
        release: k8s
      - name: kubelet
        release: k8s
        properties:
          labels:
            node-role.kubernetes.io/master: ''
            bosh/deployment:     '(deployment)'
            bosh/instance-group: '(name)'
            bosh/instance-id:    '(id)'

      - name: nfs
        release: k8s

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: tls-cm
    type: certificate
    options:
      is_ca: yes
      common_name: internal

  - name: encryption-key
    type: password
    options:
      length: 32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
