name: tinynetes

instance_groups:
  - name:      k8s
    instances: 1
    azs:       [z1]

    networks:
      - name: default
    jobs:
      - name: etcd
        release: k8s
      - name: control
        release: k8s
        properties:
          kubelet:
            instance-groups: [k8s.default]
          dashboard:
            enabled: true
            cluster-admin: true

          apiserver:
            additional-sans:
              - 10.245.0.1
          cluster:
            name: tinynetes
          encryption:
            key: ((encryption-key))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            sa:
              certificate: ((tls-sa.certificate))
              key:         ((tls-sa.private_key))

      - name: runtime-runc
        release: k8s
        properties:
          cni: flannel
      - name: net-flannel
        release: k8s
      - name: kubelet
        release: k8s
      - name: nfs
        release: k8s

      - name: jumpbox
        release: k8s
      - name: smoke-tests
        release: k8s
    persistent_disk: 20_000
    stemcell:  default
    vm_resources:
      cpu: 2
      ram: 2048
      ephemeral_disk_size: 20_000
    vm_extensions: [ kubelet ]

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-sa
    type: certificate
    options:
      is_ca: yes
      common_name: sa

  - name: encryption-key
    type: password
    options:
      length: 32
      # include_special: yes # only valid with credhub, breaks --vars-store

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-bionic
    version: latest

releases:
- name: k8s
  sha1: a6a318dabcdcb9e7a814449b473c7c6411aef640
  stemcell:
    os: ubuntu-bionic
    version: "1.204"
  url: https://s3.eu-west-3.amazonaws.com/gk-k8s-boshrelease/compiled-releases/k8s/k8s-1.20.0-ubuntu-bionic-1.204-20241112-234513-658695209-20241112234532.tgz
  version: 1.20.0
